name: build
on: [create, workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      LISP: sbcl-bin
    steps:
      - name: Restore cache
        id: cache-ql
        uses: actions/cache@v3
        with:
          path: |
            ~/.roswell
            ~/.cache/common-lisp
            ~/AppData/Local/cache
          key: ${{ runner.os }}-ql
      - name: Install Lisp
        uses: 40ants/setup-lisp@v2
      - uses: actions/checkout@v1
      - name: Build the library
        run: |
          ros run -- --noinform \
               --eval '(asdf:load-asd "/home/runner/work/ldapper/ldapper/ldapper.asd")' \
               --eval '(ql:quickload :ldapper)' \
               --non-interactive
      - name: Build the binary
        run: |
          ros run -- --noinform \
               --eval '(asdf:load-asd "/home/runner/work/ldapper/ldapper/ldapper.asd")' \
               --eval '(asdf:make :ldapper)' \
               --non-interactive
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          allowUpdates: true
          name: Release ${{ github.ref_name }}
          artifacts: ldapper
